export const GET_RECEIVE_REQUEST = "BAR.GET_RECEIVE_REQUEST";
export const GET_RECEIVE_SUCCESS = "BAR.GET_RECEIVE_SUCCESS";
export const GET_RECEIVE_FAILURE = "BAR.GET_RECEIVE_FAILURE";

export const GET_SEND_REQUEST = "BAR.GET_SEND_REQUEST";
export const GET_SEND_SUCCESS = "BAR.GET_SEND_SUCCESS";
export const GET_SEND_FAILURE = "BAR.GET_SEND_FAILURE";

export const GET_ITEM_CHART_REQUEST = "BAR.GET_ITEM_CHART_REQUEST";
export const GET_ITEM_CHART_SUCCESS = "BAR.GET_ITEM_CHART_SUCCESS";
export const GET_ITEM_CHART_FAILURE = "BAR.GET_ITEM_CHART_FAILURE";

export const GET_TODAY_POST = "BAR.GET_TODAY_POST";
